<% PASSWORD_FILE = File.join(RAILS_ROOT, '..', '..', 'shared', 'config', 'dbpassword') %>

development:
  adapter: mysql
  database: coledge_development
  username: root
  password: r00t
  host: localhost
  encoding: utf8

test: &TEST
  adapter: mysql
  database: coledge_test
  username: root
  password: r00t
  host: localhost
  encoding: utf8
  
staging:
  adapter: mysql
  database: coledge_staging
  username: coledge
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
  
production:
  adapter: mysql
  database: coledge_production
  username: coledge
  password: <%= File.read(PASSWORD_FILE).chomp if File.readable? PASSWORD_FILE %>
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock

cucumber:
  <<: *TEST